version: '2'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: keycloak
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./config/todo-app-realm.json:/opt/keycloak/data/import/realm.json
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm"

  todo-db:
    image: postgres:14-alpine
    container_name: todo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - todo-db:/var/lib/postgresql/data

volumes:
  todo-db: {}